export const ActionTypes = {
    LOGIN : "LOGIN",
    LOGOUT : "LOGOUT",
    ADD_GETEWAYS : "ADD_GETEWAYS",
    NEW_SALES : "NEW_SALES",
    NEW_CRYPTO:"NEW_CRYPTO",
    NEW_TRANSFER:"NEW_TRANSFER",
    NEW_DIGITAL:"NEW_DIGITAL",
    NEW_SETTING:"NEW_SETTING",
    NEW_NEWS:"NEW_NEWS",
    NEW_USER:"NEW_USER",
    NEW_CARDS:"NEW_CARDS",
    NEW_FILTER:"NEW_FILTER",
    NEW_BOUQUETS:"NEW_BOUQUETS",
    NEW_FILTER_BOUQUETS:"NEW_FILTER_BOUQUETS",
    CHANGE_THEME:"CHANGE_THEME",
    NEW_NOTY:"NEW_NOTY",
    NEW_COUNT_NOTY:"NEW_COUNT_NOTY",
    TOGGLE_MENU:"TOGGLE_MENU"
     
 }